package com.xgf.mybatis_generator.bean;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hourseRegister
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String hourseRegister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.friends
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String[] friends;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hobbys
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String[] hobbys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.carrers
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String carrers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remark
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hourseRegister
     *
     * @return the value of user.hourseRegister
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String getHourseRegister() {
        return hourseRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hourseRegister
     *
     * @param hourseRegister the value for user.hourseRegister
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setHourseRegister(String hourseRegister) {
        this.hourseRegister = hourseRegister == null ? null : hourseRegister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.friends
     *
     * @return the value of user.friends
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String[] getFriends() {
        return friends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.friends
     *
     * @param friends the value for user.friends
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setFriends(String[] friends) {
        this.friends = friends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hobbys
     *
     * @return the value of user.hobbys
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String[] getHobbys() {
        return hobbys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hobbys
     *
     * @param hobbys the value for user.hobbys
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setHobbys(String[] hobbys) {
        this.hobbys = hobbys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.carrers
     *
     * @return the value of user.carrers
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String getCarrers() {
        return carrers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.carrers
     *
     * @param carrers the value for user.carrers
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setCarrers(String carrers) {
        this.carrers = carrers == null ? null : carrers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remark
     *
     * @return the value of user.remark
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remark
     *
     * @param remark the value for user.remark
     *
     * @mbg.generated Sat Sep 26 16:12:52 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}